const STORAGE_URL='spx-supabase-url',STORAGE_KEY='spx-supabase-publishable-key';let db=null;const $=id=>document.getElementById(id),show=id=>$(id).classList.remove('hidden'),hide=id=>$(id).classList.add('hidden');const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function notify(text,error=false){$('message').className=`message${error?' error':''}`;$('message').textContent=text}function setConnection(online){$('connection-status').textContent=online?'Supabase conectado':'Não conectado';$('connection-status').classList.toggle('online',online)}
async function connect(url,key){db=window.supabase.createClient(url,key);const{data:{session}}=await db.auth.getSession();setConnection(true);hide('setup-panel');if(session){hide('login-panel');show('editor-panel');await loadModels()}else{show('login-panel');hide('editor-panel')}}
$('setup-form').addEventListener('submit',async e=>{e.preventDefault();const url=$('supabase-url').value.trim().replace(/\/$/,''),key=$('supabase-key').value.trim();localStorage.setItem(STORAGE_URL,url);localStorage.setItem(STORAGE_KEY,key);try{await connect(url,key)}catch(error){setConnection(false);alert(`Não foi possível conectar: ${error.message}`)}});
$('login-form').addEventListener('submit',async e=>{e.preventDefault();const{error}=await db.auth.signInWithPassword({email:$('login-email').value.trim(),password:$('login-password').value});if(error)return alert(`Entrada não autorizada: ${error.message}`);hide('login-panel');show('editor-panel');await loadModels()});
$('change-connection').addEventListener('click',()=>{hide('login-panel');show('setup-panel')});$('reload-models').addEventListener('click',loadModels);$('logout').addEventListener('click',async()=>{await db.auth.signOut();hide('editor-panel');show('login-panel');setConnection(true)});
async function loadModels(){const{data,error}=await db.from('modelos_placa').select('*').order('ordem');if(error)return notify(`Erro ao carregar: ${error.message}`,true);$('models-grid').innerHTML=data.map(m=>`<article class="model-card" data-id="${esc(m.id)}"><header><div><h2>${esc(m.nome)}</h2><div class="model-id">Código: ${esc(m.id)}</div></div></header><div class="model-fields"><label><span>Nome exibido</span><input data-field="nome" value="${esc(m.nome)}"></label><label><span>Descrição</span><textarea data-field="descricao">${esc(m.descricao)}</textarea></label><div class="model-row"><label><span>Ordem</span><input data-field="ordem" type="number" min="0" value="${Number(m.ordem)||0}"></label><label class="switch"><input data-field="ativo" type="checkbox" ${m.ativo?'checked':''}> Modelo ativo</label></div><label><span>Configuração avançada (JSON)</span><textarea data-field="configuracao">${esc(JSON.stringify(m.configuracao||{},null,2))}</textarea></label></div><button class="primary save-model" type="button">Salvar este modelo</button></article>`).join('')}
$('models-grid').addEventListener('click',async e=>{const button=e.target.closest('.save-model');if(!button)return;const card=button.closest('.model-card'),field=name=>card.querySelector(`[data-field="${name}"]`);let configuracao;try{configuracao=JSON.parse(field('configuracao').value||'{}')}catch{return notify('A configuração JSON deste modelo não é válida.',true)}button.disabled=true;button.textContent='Salvando...';const{error}=await db.from('modelos_placa').update({nome:field('nome').value.trim(),descricao:field('descricao').value.trim(),ordem:Number(field('ordem').value)||0,ativo:field('ativo').checked,configuracao}).eq('id',card.dataset.id);button.disabled=false;button.textContent='Salvar este modelo';if(error)return notify(`Não foi possível salvar: ${error.message}`,true);notify('Alteração salva no Supabase com sucesso.');await loadModels()});
const publicConfig=window.SPX_SUPABASE||{},savedUrl=publicConfig.url||localStorage.getItem(STORAGE_URL),savedKey=publicConfig.publishableKey||localStorage.getItem(STORAGE_KEY);if(savedUrl&&savedKey){$('supabase-url').value=savedUrl;$('supabase-key').value=savedKey;connect(savedUrl,savedKey).catch(error=>{setConnection(false);show('setup-panel');alert(error.message)})}
